In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\insurance.csv')

In [4]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [9]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline


X = df.drop("charges", axis=1)
y = df["charges"]   

num_cols = ['age', 'bmi', 'children']
cat_cols = ['sex', 'smoker', 'region']

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

processing = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

X_processed = processing.fit_transform(X)

In [37]:
df1 = pd.read_excel(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\Online Retail.xlsx')

In [29]:
df1

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [38]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

df1["InvoiceDate"] = pd.to_datetime(df1["InvoiceDate"])

df1["InvoiceYear"] = df1["InvoiceDate"].dt.year
df1["InvoiceMonth"] = df1["InvoiceDate"].dt.month
df1["InvoiceDay"] = df1["InvoiceDate"].dt.day
df1["InvoiceHour"] = df1["InvoiceDate"].dt.hour
df1["DayOfWeek"] = df1["InvoiceDate"].dt.dayofweek

df1 = df1.drop(["InvoiceNo", "Description", "InvoiceDate"], axis=1)


X = df1.drop("UnitPrice", axis=1)
y = df1["UnitPrice"]


num_cols = ["Quantity","InvoiceYear","InvoiceMonth","InvoiceDay","InvoiceHour","DayOfWeek"]

cat_cols = ["Country","StockCode"]

X[cat_cols] = X[cat_cols].astype(str)

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder())
])

processing = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

X_processed = processing.fit_transform(X)

In [25]:
df1['StockCode'].unique()

array(['85123A', 71053, '84406B', ..., '90214U', '47591b', 23843],
      shape=(4070,), dtype=object)

In [40]:
df1

,StockCode,Quantity,UnitPrice,CustomerID,Country,InvoiceYear,InvoiceMonth,InvoiceDay,InvoiceHour,DayOfWeek
0,85123A,6,2.55,17850.0,United Kingdom,2010,12,1,8,2
1,71053,6,3.39,17850.0,United Kingdom,2010,12,1,8,2
2,84406B,8,2.75,17850.0,United Kingdom,2010,12,1,8,2
3,84029G,6,3.39,17850.0,United Kingdom,2010,12,1,8,2
4,84029E,6,3.39,17850.0,United Kingdom,2010,12,1,8,2
...,...,...,...,...,...,...,...,...,...,...
541904,22613,12,0.85,12680.0,France,2011,12,9,12,4
541905,22899,6,2.10,12680.0,France,2011,12,9,12,4
541906,23254,4,4.15,12680.0,France,2011,12,9,12,4
541907,23255,4,4.15,12680.0,France,2011,12,9,12,4
541908,22138,3,4.95,12680.0,France,2011,12,9,12,4

In [ ]:
# num_features = num_cols

# cat_features = cat_cols  

# all_features = num_features + cat_features

# df_clean = pd.DataFrame(X_processed, columns=all_features)
# df_clean.head()