In [2]:
from pathlib import Path
import pandas as pd
csv_path = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\world_population.csv')
csv_path

WindowsPath('C:/Users/konta/Documents/DIV_Academy/Module2(From_29_nov)/data/world_population.csv')

In [4]:
df = pd.read_csv(csv_path)

In [9]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [7]:
df['2022 Population'].to_numpy()

array([4.11287710e+07, 2.84232100e+06, 4.49032250e+07, 4.42730000e+04,
       7.98240000e+04, 3.55889870e+07, 1.58570000e+04, 9.37630000e+04,
       4.55103180e+07, 2.78046900e+06, 1.06445000e+05, 2.61774130e+07,
       8.93961700e+06, 1.03580740e+07, 4.09984000e+05, 1.47223300e+06,
       1.71186372e+08, 2.81635000e+05, 9.53495400e+06, 1.16559300e+07,
       4.05272000e+05, 1.33528640e+07, 6.41840000e+04, 7.82455000e+05,
       1.22241100e+07, 3.23352600e+06, 2.63029600e+06, 2.15313498e+08,
       3.13050000e+04, 4.49002000e+05, 6.78195300e+06, 2.26737620e+07,
       1.28895760e+07, 1.67678420e+07, 2.79145360e+07, 3.84543270e+07,
       5.93149000e+05, 6.87060000e+04, 5.57914400e+06, 1.77233150e+07,
       1.96037330e+07, 1.42588734e+09, 5.18740240e+07, 8.36774000e+05,
       1.70110000e+04, 5.18082900e+06, 4.03035800e+06, 1.12121910e+07,
       1.91163000e+05, 1.25148800e+06, 1.04939860e+07, 5.88226100e+06,
       1.12084900e+06, 7.27370000e+04, 1.12288210e+07, 9.90102120e+07,
       1.80010000e+07, 1.10990103e+08, 6.33639200e+06, 1.67490800e+06,
       3.68403200e+06, 1.32606200e+06,            nan, 1.23379924e+08,
       3.78000000e+03, 5.30900000e+04, 9.29766000e+05, 5.54074500e+06,
       6.46266280e+07, 3.04557000e+05, 3.06279000e+05, 2.38899200e+06,
       2.70599200e+06, 3.74438500e+06, 8.33698430e+07, 3.34758700e+07,
       3.26490000e+04, 1.03849710e+07, 5.64660000e+04, 1.25438000e+05,
       3.95752000e+05, 1.71774000e+05, 1.78439080e+07, 6.33010000e+04,
       1.38593410e+07, 2.10556600e+06, 8.08726000e+05, 1.15849960e+07,
       1.04328600e+07, 7.48886500e+06, 9.96730800e+06, 3.72899000e+05,
       1.41717317e+09, 2.75501339e+08, 8.85505700e+07, 4.44961220e+07,
       5.02310900e+06, 8.45190000e+04, 9.03830900e+06, 5.90374740e+07,
       2.81605420e+07, 2.82737700e+06, 1.23951692e+08, 1.10778000e+05,
       1.12858690e+07, 1.93979980e+07, 5.40274870e+07, 1.31232000e+05,
       4.26887300e+06, 6.63062300e+06, 7.52947500e+06, 1.85065100e+06,
       5.48973900e+06, 2.30582500e+06, 5.30268100e+06, 6.81234100e+06,
       3.93270000e+04, 2.75005500e+06, 6.47599000e+05, 6.95168000e+05,
       2.96117140e+07, 2.04053170e+07, 3.39382210e+07, 5.23787000e+05,
       2.25935900e+07, 5.33286000e+05, 4.15690000e+04, 3.67507000e+05,
       4.73613900e+06, 1.29946900e+06, 3.26101000e+05, 1.27504125e+08,
       1.14164000e+05, 3.27299600e+06, 3.64690000e+04, 3.39836600e+06,
       6.27082000e+05, 4.39000000e+03, 3.74579710e+07, 3.29695170e+07,
       5.41793060e+07, 2.56701200e+06, 1.26680000e+04, 3.05475800e+07,
       1.75640140e+07, 2.89950000e+05, 5.18528800e+06, 6.94839200e+06,
       2.62079770e+07, 2.18541212e+08, 1.93400000e+03, 2.60694160e+07,
       2.09359900e+06, 4.95510000e+04,            nan, 4.57629800e+06,
       2.35824862e+08,            nan, 5.25007200e+06, 4.40858100e+06,
       1.01426190e+07, 6.78074400e+06, 3.40495880e+07, 1.15559009e+08,
       3.98571450e+07, 1.02708650e+07, 3.25240700e+06, 2.69512200e+06,
       5.97042400e+06, 9.74052000e+05, 1.96592670e+07, 1.44713314e+08,
       1.37766980e+07, 1.09670000e+04, 4.76570000e+04, 1.79857000e+05,
       3.17910000e+04, 5.86200000e+03, 1.03948000e+05, 2.22382000e+05,
       3.36600000e+04, 2.27380000e+05, 3.64088200e+07, 1.73164490e+07,
       7.22136500e+06, 1.07118000e+05, 8.60571800e+06, 5.97568900e+06,
       4.41750000e+04, 5.64345300e+06, 2.11984400e+06, 7.24273000e+05,
       1.75975110e+07, 5.98938850e+07, 5.18158100e+07, 1.09131640e+07,
       4.75586300e+07, 2.18321430e+07, 4.68742040e+07, 6.18040000e+05,
       1.05493470e+07, 8.74047200e+06, 2.21252490e+07, 2.38933940e+07,
       9.95278700e+06, 6.54977480e+07, 7.16970300e+07,            nan,
       8.84869900e+06, 1.87100000e+03, 1.06858000e+05, 1.53104400e+06,
       1.23561170e+07, 8.53412410e+07, 6.43077000e+06, 4.57030000e+04,
       1.13120000e+04, 4.72495850e+07, 3.97017390e+07, 9.44112900e+06,
       6.75089360e+07, 3.38289857e+08, 9.94650000e+04, 3.42279400e+06,
       3.46276520e+07, 3.26740000e+05, 5.10000000e+02, 2.83016960e+07,
       9.81868560e+07, 1.15720000e+04, 5.75986000e+05, 3.36966140e+07,
       2.00176750e+07, 1.63205370e+07])

In [12]:
df.iloc[2]

Rank                                   34
CCA3                                  DZA
Country                           Algeria
Capital                           Algiers
Continent                          Africa
2022 Population                44903225.0
2020 Population                43451666.0
2015 Population                39543154.0
2010 Population                35856344.0
2000 Population                30774621.0
1990 Population                25518074.0
1980 Population                18739378.0
1970 Population                13795915.0
Area (km²)                      2381741.0
Density (per km²)                 18.8531
Growth Rate                        1.0164
World Population Percentage          0.56
Name: 2, dtype: object

In [29]:
x = '->'
s = pd.Series([1, 2, 3, 4, 5], index=[f'One   {x}', f'Two   {x}', f'Three {x}', f'Four  {x}', f'Five  {x}'])
s.to_dict().items()

dict_items([('One   ->', 1), ('Two   ->', 2), ('Three ->', 3), ('Four  ->', 4), ('Five  ->', 5)])

In [34]:
l = [1, 2, 10, 4]
l[l.index(10)] = 100
l

[1, 2, 100, 4]

In [ ]:
a = pd.Series(
    {
        1:1,
        2:2
    }
)

b = pd.Series(
    {
        1:3,
        3:4
    }
)

a + b

1    4.0
2    NaN
3    NaN
dtype: float64

In [5]:
import seaborn as sb
df = sb.load_dataset("titanic")
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [4]:
import pandas as pd
from pathlib import Path
csv_path = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\world_population.csv')
df = pd.read_csv(csv_path)
df.head()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [ ]:
# print(s.value_counts(normalize=True))
# print(f'{int(57 / s.value_counts().sum() * 100)} %')


s = df['2022 Population']

def f(pop):
    if pop > 100_000_000:
        return 'Big country'
    else:
        return 'Small country'

df['Size Category'] = s.apply(f)
df[['Country', '2022 Population', 'Size Category']]

               Country  2022 Population  Size Category
0          Afghanistan       41128771.0  Small country
1              Albania        2842321.0  Small country
2              Algeria       44903225.0  Small country
3       American Samoa          44273.0  Small country
4              Andorra          79824.0  Small country
..                 ...              ...            ...
229  Wallis and Futuna          11572.0  Small country
230     Western Sahara         575986.0  Small country
231              Yemen       33696614.0  Small country
232             Zambia       20017675.0  Small country
233           Zimbabwe       16320537.0  Small country

[234 rows x 3 columns]

:

In [4]:
import numpy as np
import pandas as pd

s_yash = pd.Series([10,20,30], index=['ali', 'vali', 'gulnar'])
s_boy = pd.Series([150,160,170],index=['ali', 'hasan', 'gulnar'])

df1 = pd.DataFrame({
    'yash' : s_yash,
    'boy' : s_boy,
})

df2 = pd.DataFrame(
	np.array(
        [
            [ 10., 150.],
			[ 30., 170.],
			[ np.nan, 160.],
			[ 20.,  np.nan]
        ]
    ), 
    columns=['yash', 'boy'],
    index=['ali', 'vali', 'hesen', 'gulnar']
)
df2

df1.to_excel('output.xlsx', index=False)

In [1]:
%pip install openpyxl xlsxwriter

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlsxwriter, et-xmlfile, openpyxl

   ---------------------------------------- 0/3 [xlsxwriter]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ---------------------------------------- 3/3 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlsxwriter-3.2.9
Note: you may need to restart the kernel to use updated packages.

In [6]:
pd.read_excel('output.xlsx')

   yash    boy
0  10.0  150.0
1  30.0  170.0
2   NaN  160.0
3  20.0    NaN
4  30.0  120.0

In [ ]:
import pandas as pd
data = {'A':[1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10], 'C': [11, 12, 13, 14, 15]}
df = pd.DataFrame(data)

df.columns = ['X', 'Y', 'Z']

filtered_df = df[df['X'] > 3]
filtered_df

   X   Y   Z
3  4   9  14
4  5  10  15

In [10]:
print(filtered_df.describe())

              X          Y          Z
count  2.000000   2.000000   2.000000
mean   4.500000   9.500000  14.500000
std    0.707107   0.707107   0.707107
min    4.000000   9.000000  14.000000
25%    4.250000   9.250000  14.250000
50%    4.500000   9.500000  14.500000
75%    4.750000   9.750000  14.750000
max    5.000000  10.000000  15.000000