In [4]:
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset("titanic")
df.head()



# TAPŞIRIQ 1:
# 1. Yalnız qadın (sex == 'female') sərnişinləri seç
# 2. Yaşı (age) 18-dən böyük olanları saxla
# 3. Yalnız aşağıdakı sütunları göstər:
#    - survived
#    - pclass
#    - age
#    - fare

m = (df['sex'] == 'female') & (df['age'] > 18)

result = df.loc[m, ['survived', 'pclass', 'age', 'fare']]

result

     survived  pclass   age     fare
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
8           1       3  27.0  11.1333
11          1       1  58.0  26.5500
..        ...     ...   ...      ...
879         1       1  56.0  83.1583
880         1       2  25.0  26.0000
882         0       3  22.0  10.5167
885         0       3  39.0  29.1250
887         1       1  19.0  30.0000

[193 rows x 4 columns]

In [5]:


# TAPŞIRIQ 2:
# 1. Dataset-in ilk 100 sətrini seç
# 2. Yalnız age, fare və survived sütunlarını götür
# 3. fare < 20 olan sətirlərdə bütün dəyərləri NaN et
#    (sətirləri silmə, yalnız maskala)

import numpy as np

df2 = df.loc[:99, ['age', 'fare', 'survived']]

mask = df2['fare'] < 20

df2.loc[mask, :] = np.nan

df2

     age     fare  survived
0    NaN      NaN       NaN
1   38.0  71.2833       1.0
2    NaN      NaN       NaN
3   35.0  53.1000       1.0
4    NaN      NaN       NaN
..   ...      ...       ...
95   NaN      NaN       NaN
96  71.0  34.6542       0.0
97  23.0  63.3583       1.0
98  34.0  23.0000       1.0
99  34.0  26.0000       0.0

[100 rows x 3 columns]

In [6]:

# TAPŞIRIQ 3:
# Yeni "age_group" adlı sütun yarat:
# - age < 18        → "Child"
# - 18 <= age < 60  → "Adult"
# - age >= 60       → "Senior"
# NaN yaşlar üçün dəyər "Unknown" olsun

conditions = [df['age'] < 18, (df['age'] >= 18) & (df['age'] < 60), df['age'] >= 60]

choices = ['Child', 'Adult', 'Senior']

df['age_group'] = np.select(conditions, choices, default='Unknown')

df[['age', 'age_group']]

      age age_group
0    22.0     Adult
1    38.0     Adult
2    26.0     Adult
3    35.0     Adult
4    35.0     Adult
..    ...       ...
886  27.0     Adult
887  19.0     Adult
888   NaN   Unknown
889  26.0     Adult
890  32.0     Adult

[891 rows x 2 columns]

In [14]:
# TAPŞIRIQ 4:
# age_filled adli sütun yarat ve age sütununun boş olanları birbaşa median ilə doldur
df['age_filled'] = df['age'].fillna(df['age'].median())
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group,age_filled
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Adult,22.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Adult,38.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Adult,26.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Adult,35.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Adult,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,Adult,27.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,Adult,19.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,Unknown,28.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,Adult,26.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Adult,32.0

In [19]:
# TAPŞIRIQ 5:
# 1. Eyni sex, age və fare olan təkrarlanan sətirləri sil
# 2. Qalan məlumatları:
#    - əvvəl fare azalan
#    - sonra age artan
#    şəkildə sırala
# 3. Yalnız sex, age, fare sütunlarını saxla

result = (df.drop_duplicates(subset=['sex', 'age', 'fare']).sort_values(by=['fare', 'age'], ascending=[False, True])[['sex', 'age', 'fare']])

result

        sex   age      fare
258  female  35.0  512.3292
737    male  35.0  512.3292
679    male  36.0  512.3292
27     male  19.0  263.0000
88   female  23.0  263.0000
..      ...   ...       ...
822    male  38.0    0.0000
806    male  39.0    0.0000
263    male  40.0    0.0000
597    male  49.0    0.0000
277    male   NaN    0.0000

[750 rows x 3 columns]

In [17]:
# TAPŞIRIQ 6:
# 1. Hər pclass üzrə:
#    - sağ qalmayan (survived == 0) sərnişinlərin sayını tap
# 2. Ən çox itki olan pclass-ı müəyyən et
# pclass üzrə sağ qalmayanların sayı

loss_by_pclass = (df[df['survived'] == 0].groupby('pclass').size())

most_loss_pclass = loss_by_pclass.idxmax()

loss_by_pclass, most_loss_pclass

(pclass
 1     80
 2     97
 3    372
 dtype: int64,
 np.int64(3))