In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\housing.csv')

In [3]:
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [7]:
num_cols = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']
cat_cols = ['ocean_proximity']

from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import FunctionTransformer

num_pipeline = Pipeline(steps=[
    ("imp", SimpleImputer(strategy='median')),
    ("log"), FunctionTransformer()
    ("scl", StandardScaler())
])

cat_pipeline = Pipeline(steps=[
    ("imp", SimpleImputer(strategy='most_frequent')),
    ("enc", OneHotEncoder())
])

preprossesing = ColumnTransformer(transformers=[
    ("NUM", num_pipeline, num_cols),
    ("CAT", cat_pipeline, cat_cols)
])

In [19]:
preprossesing

ColumnTransformer(transformers=[('NUM',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(strategy='median')),
                                                 ('scl', StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income',
                                  'median_house_value']),
                                ('CAT',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('enc', OneHotEncoder())]),
                                 ['ocean_proximity'])])

In [14]:
num_pipeline

Pipeline(steps=[('imp', SimpleImputer(strategy='median')),
                ('scl', StandardScaler())])

In [15]:
cat_pipeline

Pipeline(steps=[('imp', SimpleImputer(strategy='most_frequent')),
                ('enc', OneHotEncoder())])

In [21]:
df_transformed = preprossesing.fit_transform(df)

In [25]:
df_tr = pd.DataFrame(df_transformed, columns=preprossesing.get_feature_names_out())

In [26]:
df_tr.head(5)

,NUM__longitude,NUM__latitude,NUM__housing_median_age,NUM__total_rooms,NUM__total_bedrooms,NUM__population,NUM__households,NUM__median_income,NUM__median_house_value,CAT__ocean_proximity_<1H OCEAN,CAT__ocean_proximity_INLAND,CAT__ocean_proximity_ISLAND,CAT__ocean_proximity_NEAR BAY,CAT__ocean_proximity_NEAR OCEAN
0,-1.327835,1.052548,0.982143,-0.804819,-0.972476,-0.974429,-0.977033,2.344766,2.129631,0.0,0.0,0.0,1.0,0.0
1,-1.322844,1.043185,-0.607019,2.045890,1.357143,0.861439,1.669961,2.332238,1.314156,0.0,0.0,0.0,1.0,0.0
2,-1.332827,1.038503,1.856182,-0.535746,-0.827024,-0.820777,-0.843637,1.782699,1.258693,0.0,0.0,0.0,1.0,0.0
3,-1.337818,1.038503,1.856182,-0.624215,-0.719723,-0.766028,-0.733781,0.932968,1.165100,0.0,0.0,0.0,1.0,0.0
4,-1.337818,1.038503,1.856182,-0.462404,-0.612423,-0.759847,-0.629157,-0.012881,1.172900,0.0,0.0,0.0,1.0,0.0