In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [4]:
csv_path = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\housing.csv')
df = pd.read_csv(csv_path)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [6]:
df['income_cat'] = pd.cut(
    df['median_income'],
    bins=[0, 1.5, 3, 4.5, 6, np.inf],
    labels=[1, 2, 3, 4, 5],
)

df[['income_cat', 'median_income']].head()

  income_cat  median_income
0          5         8.3252
1          5         8.3014
2          5         7.2574
3          4         5.6431
4          3         3.8462

In [7]:
from sklearn.model_selection import train_test_split

strat_train_set, strat_test_set = train_test_split(df, test_size=0.2, stratify=df['income_cat'])

In [9]:
df_strat = strat_train_set.copy()
df_strat.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
16002,-117.83,33.66,15.0,2355.0,438.0,747.0,450.0,6.5356,272800.0,<1H OCEAN,5
14959,-121.96,38.35,20.0,1415.0,266.0,667.0,250.0,4.0938,117300.0,INLAND,3
5665,-122.04,37.62,35.0,657.0,118.0,328.0,134.0,3.8125,204200.0,NEAR BAY,3
8647,-118.58,34.15,21.0,3856.0,547.0,1422.0,535.0,8.4196,450700.0,<1H OCEAN,5
7184,-118.22,33.96,42.0,1380.0,331.0,1290.0,288.0,2.8000,161800.0,<1H OCEAN,2

In [15]:
df_num = df_strat.select_dtypes(include='number')
df_cat = df_strat.select_dtypes(include='object')

In [17]:
null_mask = df_num.sort_index().isna().any(axis=1)
df_num.loc[null_mask].head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
12962,-118.36,33.96,26.0,3543.0,NaN,2742.0,951.0,2.5504,151300.0
14938,-124.00,40.92,29.0,1429.0,NaN,672.0,266.0,2.9485,98800.0
9531,-119.44,36.58,37.0,1054.0,NaN,879.0,257.0,2.5234,63500.0
8198,-117.98,33.73,18.0,3833.0,NaN,2192.0,996.0,3.4679,219700.0
3697,-117.20,32.79,29.0,1213.0,NaN,654.0,246.0,4.5987,255600.0
19782,-119.75,34.45,6.0,2864.0,NaN,1404.0,603.0,5.5073,263800.0
15717,-117.91,33.87,29.0,1121.0,NaN,762.0,276.0,2.5000,143800.0
366,-122.50,37.75,44.0,1819.0,NaN,1137.0,354.0,3.4919,271800.0
17292,-117.09,32.77,31.0,3062.0,NaN,1263.0,539.0,3.0875,291500.0
19065,-118.43,34.20,28.0,3386.0,NaN,2240.0,737.0,3.0221,290100.0