In [20]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\housing.csv')

In [4]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [6]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2)
train_set.shape, test_set.shape

((16512, 10), (4128, 10))

In [7]:
df_num = df.select_dtypes(include='number')
df_cat = df.select_dtypes(include='object')

In [12]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(df_num)

X = ss.transform(df_num)
df_num_ss = pd.DataFrame(X, columns=ss.get_feature_names_out())

In [13]:
df_num_ss

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-1.327835,1.052548,0.982143,-0.804819,-0.970325,-0.974429,-0.977033,2.344766,2.129631
1,-1.322844,1.043185,-0.607019,2.045890,1.348276,0.861439,1.669961,2.332238,1.314156
2,-1.332827,1.038503,1.856182,-0.535746,-0.825561,-0.820777,-0.843637,1.782699,1.258693
3,-1.337818,1.038503,1.856182,-0.624215,-0.718768,-0.766028,-0.733781,0.932968,1.165100
4,-1.337818,1.038503,1.856182,-0.462404,-0.611974,-0.759847,-0.629157,-0.012881,1.172900
...,...,...,...,...,...,...,...,...,...
20635,-0.758826,1.801647,-0.289187,-0.444985,-0.388895,-0.512592,-0.443449,-1.216128,-1.115804
20636,-0.818722,1.806329,-0.845393,-0.888704,-0.920488,-0.944405,-1.008420,-0.691593,-1.124470
20637,-0.823713,1.778237,-0.924851,-0.174995,-0.125472,-0.369537,-0.174042,-1.142593,-0.992746
20638,-0.873626,1.778237,-0.845393,-0.355600,-0.305834,-0.604429,-0.393753,-1.054583,-1.058608
20639,-0.833696,1.750146,-1.004309,0.068408,0.185416,-0.033977,0.079672,-0.780129,-1.017878

In [17]:
from sklearn.ensemble import IsolationForest

iso_forest = IsolationForest()
# iso_forest.fit(df_num)
# pred = iso_forest.predict(df_num)

pred = iso_forest.fit_predict(df_num)

pred

array([-1, -1,  1, ...,  1,  1,  1], shape=(20640,))

In [19]:
outlier_mask = (pred == -1)
df_num.loc[outlier_mask]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
57,-122.28,37.82,52.0,1489.0,335.0,728.0,244.0,0.8172,85300.0
59,-122.29,37.82,2.0,158.0,43.0,94.0,57.0,2.5625,60000.0
61,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0
...,...,...,...,...,...,...,...,...,...
20603,-121.54,39.13,18.0,4289.0,1021.0,2707.0,939.0,1.3375,59600.0
20620,-121.48,39.05,40.0,198.0,41.0,151.0,48.0,4.5625,100000.0
20625,-121.52,39.12,37.0,102.0,17.0,29.0,14.0,4.1250,72000.0
20627,-121.32,39.13,5.0,358.0,65.0,169.0,59.0,3.0000,162500.0
20629,-121.39,39.12,28.0,10035.0,1856.0,6912.0,1818.0,2.0943,108300.0

In [21]:
np.unique_counts(pred)

UniqueCountsResult(values=array([-1,  1]), counts=array([ 2934, 17706]))

In [29]:
m = df_num.median()
q1 = df_num.quantile(q=0.25)
q3 = df_num.quantile(q=0.75)
iqr = np.abs(q3 - q1)

lower_fence = q1 - 1.5*iqr 
upper_fence = q3 + 1.5*iqr 

outlier_mask = (df_num < lower_fence) | (df_num > upper_fence)
outlier_mask = outlier_mask.any(axis=1)
df_num.loc[outlier_mask]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
89,-122.27,37.80,52.0,249.0,78.0,396.0,85.0,1.2434,500001.0
95,-122.26,37.80,36.0,5329.0,2477.0,3469.0,2323.0,2.0096,130000.0
96,-122.26,37.82,31.0,4596.0,1331.0,2048.0,1180.0,2.8345,183800.0
...,...,...,...,...,...,...,...,...,...
20544,-121.76,38.55,23.0,8800.0,1857.0,6330.0,1832.0,2.0650,219400.0
20563,-121.75,38.67,9.0,12139.0,2640.0,6837.0,2358.0,3.1250,132500.0
20567,-121.79,38.66,15.0,6809.0,1052.0,3060.0,1060.0,5.3064,165000.0
20604,-121.54,39.12,17.0,4251.0,899.0,3265.0,934.0,2.3496,65000.0
20629,-121.39,39.12,28.0,10035.0,1856.0,6912.0,1818.0,2.0943,108300.0

In [30]:
m = df_num.mean()
s = np.abs(df_num.std())

outlier_mask = (np.abs(df_num - m) > 3*s).any(axis=1)
df_num.loc[outlier_mask]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
95,-122.26,37.80,36.0,5329.0,2477.0,3469.0,2323.0,2.0096,130000.0
117,-117.47,34.12,6.0,10565.0,1767.0,5690.0,1555.0,4.1797,141000.0
146,-122.51,38.06,24.0,9493.0,1935.0,5162.0,1880.0,3.0742,118800.0
158,-116.39,33.69,10.0,11659.0,2007.0,2186.0,1083.0,6.9833,238800.0
212,-122.04,37.39,5.0,8745.0,2211.0,3959.0,2019.0,4.7685,280100.0
...,...,...,...,...,...,...,...,...,...
20494,-118.12,34.13,52.0,2935.0,341.0,975.0,327.0,11.7060,500001.0
20543,-121.74,38.55,33.0,6861.0,1820.0,3717.0,1767.0,1.7311,182600.0
20544,-121.76,38.55,23.0,8800.0,1857.0,6330.0,1832.0,2.0650,219400.0
20563,-121.75,38.67,9.0,12139.0,2640.0,6837.0,2358.0,3.1250,132500.0
20629,-121.39,39.12,28.0,10035.0,1856.0,6912.0,1818.0,2.0943,108300.0

In [ ]:
from sklearn.preprocessing import StandardScaler, RobustScaler