In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
csv_path = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\housing.csv')
df = pd.read_csv(csv_path)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [3]:
df['income_cat'] = pd.cut(
    df['median_income'],
    bins=[0, 1.5, 3, 4.5, 6, np.inf],
    labels=[1, 2, 3, 4, 5],
)

df[['income_cat', 'median_income']].head()

  income_cat  median_income
0          5         8.3252
1          5         8.3014
2          5         7.2574
3          4         5.6431
4          3         3.8462

In [4]:
from sklearn.model_selection import train_test_split

strat_train_set, strat_test_set = train_test_split(df, test_size=0.2, stratify=df['income_cat'])

In [5]:
df_strat = strat_train_set.copy()
df_strat.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
5115,-119.27,35.88,32.0,1393.0,343.0,1282.0,336.0,1.5069,43700.0,INLAND,2
10089,-117.31,34.41,14.0,3019.0,643.0,1639.0,582.0,1.5288,103400.0,INLAND,2
6374,-117.78,33.68,11.0,1994.0,477.0,849.0,411.0,4.0187,235600.0,<1H OCEAN,3
3651,-122.23,38.17,45.0,350.0,NaN,225.0,72.0,1.8942,216700.0,NEAR BAY,2
584,-122.14,38.16,4.0,3273.0,495.0,1497.0,454.0,5.3345,176100.0,NEAR BAY,4

In [6]:
df_num = df_strat.select_dtypes(include='number')
df_cat = df_strat.select_dtypes(include='object')

In [7]:
null_mask = df_num.sort_index().isna().any(axis=1)
df_num.loc[null_mask].head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3651,-122.23,38.17,45.0,350.0,NaN,225.0,72.0,1.8942,216700.0
1009,-120.85,37.78,25.0,421.0,NaN,303.0,106.0,2.2679,71300.0
16075,-116.91,32.83,16.0,5203.0,NaN,2515.0,862.0,4.1050,174400.0
11436,-121.30,38.58,16.0,1537.0,NaN,1125.0,375.0,2.6471,90700.0
19065,-118.43,34.20,28.0,3386.0,NaN,2240.0,737.0,3.0221,290100.0
12882,-119.46,35.14,30.0,2943.0,NaN,1565.0,584.0,2.5313,45800.0
7882,-121.97,37.34,33.0,3162.0,NaN,1553.0,686.0,3.6682,266100.0
19721,-118.29,33.73,30.0,3161.0,NaN,1865.0,771.0,2.7139,231700.0
4504,-116.66,32.79,13.0,843.0,NaN,918.0,152.0,6.2152,240600.0
4090,-121.88,37.40,9.0,6751.0,NaN,4240.0,1438.0,5.3400,257400.0

In [8]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='median')

imp.fit(df_num)

print('----------------')
print(imp.statistics_)
print(len(imp.statistics_))
print(len(df_num.columns))
print('----------------')
X = imp.transform(df_num)
df_num_tr = pd.DataFrame(X, columns=imp.get_feature_names_out(), index=df_num.index)

----------------
[-1.1852e+02  3.4270e+01  2.9000e+01  2.1275e+03  4.3400e+02  1.1675e+03
  4.0800e+02  3.5269e+00  1.8040e+05]
9
9
----------------

In [9]:
df_num_tr

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5115,-119.27,35.88,32.0,1393.0,343.0,1282.0,336.0,1.5069,43700.0
10089,-117.31,34.41,14.0,3019.0,643.0,1639.0,582.0,1.5288,103400.0
6374,-117.78,33.68,11.0,1994.0,477.0,849.0,411.0,4.0187,235600.0
3651,-122.23,38.17,45.0,350.0,434.0,225.0,72.0,1.8942,216700.0
584,-122.14,38.16,4.0,3273.0,495.0,1497.0,454.0,5.3345,176100.0
...,...,...,...,...,...,...,...,...,...
11411,-116.36,33.78,6.0,24121.0,4522.0,4176.0,2221.0,3.3799,239300.0
19745,-117.93,33.93,33.0,1626.0,378.0,1062.0,356.0,2.1944,139600.0
7743,-119.18,34.17,32.0,2388.0,467.0,1746.0,483.0,3.9331,187600.0
11046,-117.13,33.15,15.0,2241.0,381.0,997.0,390.0,3.4833,193200.0
5274,-119.24,35.77,28.0,1737.0,521.0,1764.0,514.0,1.7813,67800.0

In [10]:
df_num_tr.loc[null_mask]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3651,-122.23,38.17,45.0,350.0,434.0,225.0,72.0,1.8942,216700.0
1009,-120.85,37.78,25.0,421.0,434.0,303.0,106.0,2.2679,71300.0
16075,-116.91,32.83,16.0,5203.0,434.0,2515.0,862.0,4.1050,174400.0
11436,-121.30,38.58,16.0,1537.0,434.0,1125.0,375.0,2.6471,90700.0
19065,-118.43,34.20,28.0,3386.0,434.0,2240.0,737.0,3.0221,290100.0
...,...,...,...,...,...,...,...,...,...
7506,-122.53,38.32,22.0,3577.0,434.0,1371.0,501.0,5.7950,332300.0
14452,-120.67,40.50,15.0,5343.0,434.0,2503.0,902.0,3.5962,85900.0
19782,-119.75,34.45,6.0,2864.0,434.0,1404.0,603.0,5.5073,263800.0
17292,-117.09,32.77,31.0,3062.0,434.0,1263.0,539.0,3.0875,291500.0
18598,-118.07,34.10,32.0,4275.0,434.0,2812.0,1012.0,3.3512,214100.0

In [11]:
from sklearn.impute import KNNImputer

kimp = KNNImputer(n_neighbors=10)
kimp.fit(df_num)

X = kimp.transform(df_num)
df_num_tr2 = pd.DataFrame(X, columns=kimp.get_feature_names_out(), index=df_num.index)
df_num_tr2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5115,-119.27,35.88,32.0,1393.0,343.0,1282.0,336.0,1.5069,43700.0
10089,-117.31,34.41,14.0,3019.0,643.0,1639.0,582.0,1.5288,103400.0
6374,-117.78,33.68,11.0,1994.0,477.0,849.0,411.0,4.0187,235600.0
3651,-122.23,38.17,45.0,350.0,184.3,225.0,72.0,1.8942,216700.0
584,-122.14,38.16,4.0,3273.0,495.0,1497.0,454.0,5.3345,176100.0
...,...,...,...,...,...,...,...,...,...
11411,-116.36,33.78,6.0,24121.0,4522.0,4176.0,2221.0,3.3799,239300.0
19745,-117.93,33.93,33.0,1626.0,378.0,1062.0,356.0,2.1944,139600.0
7743,-119.18,34.17,32.0,2388.0,467.0,1746.0,483.0,3.9331,187600.0
11046,-117.13,33.15,15.0,2241.0,381.0,997.0,390.0,3.4833,193200.0
5274,-119.24,35.77,28.0,1737.0,521.0,1764.0,514.0,1.7813,67800.0

In [12]:
df_num_tr2.loc[null_mask]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3651,-122.23,38.17,45.0,350.0,184.3,225.0,72.0,1.8942,216700.0
1009,-120.85,37.78,25.0,421.0,109.5,303.0,106.0,2.2679,71300.0
16075,-116.91,32.83,16.0,5203.0,941.9,2515.0,862.0,4.1050,174400.0
11436,-121.30,38.58,16.0,1537.0,362.5,1125.0,375.0,2.6471,90700.0
19065,-118.43,34.20,28.0,3386.0,776.0,2240.0,737.0,3.0221,290100.0
...,...,...,...,...,...,...,...,...,...
7506,-122.53,38.32,22.0,3577.0,597.0,1371.0,501.0,5.7950,332300.0
14452,-120.67,40.50,15.0,5343.0,962.0,2503.0,902.0,3.5962,85900.0
19782,-119.75,34.45,6.0,2864.0,515.1,1404.0,603.0,5.5073,263800.0
17292,-117.09,32.77,31.0,3062.0,602.5,1263.0,539.0,3.0875,291500.0
18598,-118.07,34.10,32.0,4275.0,794.0,2812.0,1012.0,3.3512,214100.0

In [13]:
m = df['median_income'].mean()
s = df['median_income'].std()

m - 3*s, m + 3*s

outlier1 = df['median_income'] > m + 3*s
outlier2 = df['median_income'] < m - 3*s

df.loc[outlier1 | outlier2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
409,-117.87,33.64,26.0,3521.0,455.0,1336.0,451.0,10.2849,500001.0,<1H OCEAN,5
478,-117.58,33.60,5.0,5348.0,659.0,1862.0,555.0,11.0567,495400.0,<1H OCEAN,5
480,-118.32,34.07,52.0,2980.0,366.0,967.0,359.0,11.2185,500001.0,<1H OCEAN,5
515,-118.41,34.07,52.0,3562.0,394.0,1163.0,361.0,15.0001,500001.0,<1H OCEAN,5
546,-122.21,37.38,28.0,4518.0,578.0,1489.0,559.0,11.3176,500001.0,NEAR OCEAN,5
...,...,...,...,...,...,...,...,...,...,...,...
20392,-117.77,33.80,16.0,3973.0,483.0,1373.0,452.0,9.8074,417000.0,<1H OCEAN,5
20426,-122.08,37.84,17.0,1320.0,159.0,1722.0,141.0,11.7064,500001.0,NEAR BAY,5
20466,-117.24,32.85,22.0,3479.0,448.0,1252.0,440.0,10.0707,500001.0,NEAR OCEAN,5
20492,-117.18,33.02,15.0,3540.0,453.0,1364.0,425.0,13.6623,500001.0,NEAR OCEAN,5
20494,-118.12,34.13,52.0,2935.0,341.0,975.0,327.0,11.7060,500001.0,<1H OCEAN,5

In [14]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(df_num)
X = ss.transform(df_num)

df_num_ss = pd.DataFrame(X, columns=ss.get_feature_names_out())

o1 = (df_num_ss < -3).any(axis=1)
o2 = (df_num_ss > 3).any(axis=1)
df_num_ss.loc[o1 | o2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
34,0.697615,-0.684312,0.429781,-0.262566,-0.655012,-0.527696,-0.639007,5.837911,2.531808
75,-1.218573,0.758497,-0.285084,0.834308,0.036239,0.160260,0.159638,3.632181,2.531808
114,-1.218573,0.763182,0.032634,0.510595,-0.164295,-0.092781,-0.074492,3.158906,2.531808
115,-1.233543,0.819395,-0.602802,4.672681,6.342428,5.137615,6.639850,0.242661,0.521420
151,0.138727,-0.567201,-1.873673,-1.020639,-1.155166,-1.069801,-1.159297,4.595519,2.531808
...,...,...,...,...,...,...,...,...,...
16435,0.602803,-0.768632,-0.841090,3.151506,3.626968,2.193375,3.695009,0.466209,0.838621
16440,0.897217,-0.890428,-0.205655,0.117842,-0.454479,-0.388875,-0.451702,5.033066,2.531808
16448,-1.223563,1.086409,-0.602802,1.741892,3.070193,1.928912,3.213740,-0.675977,-0.817392
16479,0.952108,-0.937272,-1.794244,3.547917,3.249493,2.949863,3.411451,1.078355,0.283736
16507,1.610798,-0.876375,-1.794244,9.823736,9.399974,2.416544,4.478045,-0.258472,0.278550