In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

In [3]:
housing_path = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\housing.csv')

In [6]:
df = pd.read_csv(housing_path)

In [7]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [9]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [17]:
print(df['ocean_proximity'].value_counts().max())
print(df['ocean_proximity'].mode())

9136
0    <1H OCEAN
Name: ocean_proximity, dtype: object

In [28]:
ages = [23, 34, 45, 44]
mean_ = np.mean(ages)
np.sqrt(((np.sum(ages - mean_)**2) / len(ages)))

np.float64(0.0)

In [33]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2)

In [34]:
train_set

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
4087,-122.06,37.68,30.0,5367.0,1207.0,2667.0,1047.0,3.1796,170300.0,NEAR BAY
3732,-119.99,38.88,17.0,2807.0,529.0,675.0,251.0,2.7457,107800.0,INLAND
1959,-124.00,40.22,16.0,2088.0,535.0,816.0,326.0,1.3190,70700.0,<1H OCEAN
1860,-117.26,33.21,26.0,1906.0,408.0,1325.0,427.0,3.0197,136000.0,<1H OCEAN
13598,-119.20,35.37,6.0,7383.0,1095.0,3415.0,1059.0,5.3119,157300.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
15095,-118.69,34.08,23.0,204.0,40.0,117.0,41.0,9.7646,500001.0,NEAR OCEAN
5767,-120.35,40.63,33.0,240.0,49.0,63.0,22.0,3.6250,200000.0,INLAND
6467,-122.07,37.94,30.0,1260.0,276.0,707.0,221.0,2.8920,220800.0,NEAR BAY
7993,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0,INLAND
11613,-121.34,38.62,20.0,4021.0,864.0,1658.0,730.0,2.4537,153000.0,INLAND

In [35]:
test_set

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
16668,-118.54,34.17,25.0,3352.0,891.0,1815.0,860.0,2.8528,425000.0,<1H OCEAN
14188,-118.39,34.14,19.0,5076.0,1034.0,2021.0,960.0,5.5683,309200.0,<1H OCEAN
18124,-122.08,37.63,31.0,767.0,171.0,548.0,185.0,3.7614,176000.0,NEAR BAY
7785,-122.39,38.37,33.0,1066.0,191.0,403.0,163.0,6.8000,240800.0,<1H OCEAN
1790,-117.81,35.65,19.0,1124.0,290.0,598.0,261.0,1.8984,54300.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
5732,-118.20,34.05,40.0,1082.0,318.0,1085.0,273.0,1.7054,117200.0,<1H OCEAN
6199,-122.09,37.66,40.0,1340.0,313.0,766.0,271.0,3.4722,135400.0,NEAR BAY
4806,-118.23,33.93,30.0,1147.0,260.0,1219.0,210.0,2.0658,93200.0,<1H OCEAN
3682,-118.20,34.06,46.0,453.0,119.0,533.0,132.0,2.2961,112500.0,<1H OCEAN
9459,-121.90,37.44,4.0,1646.0,408.0,853.0,410.0,5.0821,265500.0,<1H OCEAN